apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "wquinoa"
          - name: PMA_HOST
            value: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: lb-phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: phpmyadmin