# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hwindom <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/13 11:43:48 by hwindom           #+#    #+#              #
#    Updated: 2020/02/13 13:53:41 by hwindom          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = srcs/*.c

all:
	gcc -Wall -Werror -Wextra  $(SRCS) -o $(NAME)

clean:
	/bin/rm -f

fclean:
	/bin/rm -f $(NAME)

re: fclean re
